#############################################################################
# Generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#  Jul 16, 2020 08:45:36 PM IST  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { \
    drugs_png "../drugs.png" \
}
vTcl:create_project_images $image_list   ;# In image.tcl


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top59 {base} {
    global vTcl
    if {$base == ""} {
        set base .top59
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 605x450+339+168
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1351 738
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Admin Page"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    label $top.lab60 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -image drugs_png -text Label 
    vTcl:DefineAlias "$top.lab60" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab61 \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 20 -weight bold -slant roman -underline 1 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -text {Pharmacy Management System} 
    vTcl:DefineAlias "$top.lab61" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab62 \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 11 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -text {Tablet Name :} 
    vTcl:DefineAlias "$top.lab62" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab68 \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 11 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -text {Dosage :} 
    vTcl:DefineAlias "$top.lab68" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab69 \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 11 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -text {Manufacturing Date :} 
    vTcl:DefineAlias "$top.lab69" "Label5" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab70 \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 11 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -text {Expiry Date :} 
    vTcl:DefineAlias "$top.lab70" "Label6" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab71 \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 11 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -text {Price :} 
    vTcl:DefineAlias "$top.lab71" "Label7" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent72 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -insertbackground black -width 306 
    vTcl:DefineAlias "$top.ent72" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent73 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -insertbackground black -width 306 
    vTcl:DefineAlias "$top.ent73" "Entry2" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent74 \
        -background white -font TkFixedFont -foreground #020202 \
        -insertbackground black -width 306 
    vTcl:DefineAlias "$top.ent74" "Entry3" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent75 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -insertbackground black -width 306 
    vTcl:DefineAlias "$top.ent75" "Entry4" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent76 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -insertbackground black -width 306 
    vTcl:DefineAlias "$top.ent76" "Entry5" vTcl:WidgetProc "Toplevel1" 1
    button $top.but77 \
        -background $vTcl(actual_gui_bg) -borderwidth 4 \
        -font {-family {DejaVu Sans} -size 11 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Delete 
    vTcl:DefineAlias "$top.but77" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but78 \
        -background $vTcl(actual_gui_bg) -borderwidth 4 \
        -font {-family {DejaVu Sans} -size 11 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Add 
    vTcl:DefineAlias "$top.but78" "Button2" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab60 \
        -in $top -x 0 -relx 0.165 -y 0 -rely 0.2 -width 0 -relwidth 0.651 \
        -height 0 -relheight 0.202 -anchor nw -bordermode ignore 
    place $top.lab61 \
        -in $top -x 0 -relx 0.067 -y 0 -rely 0.067 -width 0 -relwidth 0.865 \
        -height 0 -relheight 0.091 -anchor nw -bordermode ignore 
    place $top.lab62 \
        -in $top -x 0 -relx 0.083 -y 0 -rely 0.489 -height 0 -relheight 0.047 \
        -anchor nw -bordermode ignore 
    place $top.lab68 \
        -in $top -x 0 -relx 0.083 -y 0 -rely 0.556 -width 0 -relwidth 0.182 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab69 \
        -in $top -x 0 -relx 0.017 -y 0 -rely 0.622 -width 0 -relwidth 0.297 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab70 \
        -in $top -x 0 -relx 0.05 -y 0 -rely 0.689 -width 0 -relwidth 0.265 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab71 \
        -in $top -x 0 -relx 0.067 -y 0 -rely 0.756 -width 0 -relwidth 0.215 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.ent72 \
        -in $top -x 0 -relx 0.35 -y 0 -rely 0.489 -width 306 -relwidth 0 \
        -height 23 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent73 \
        -in $top -x 0 -relx 0.35 -y 0 -rely 0.556 -width 306 -relwidth 0 \
        -height 23 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent74 \
        -in $top -x 0 -relx 0.35 -y 0 -rely 0.622 -width 306 -relwidth 0 \
        -height 23 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent75 \
        -in $top -x 0 -relx 0.35 -y 0 -rely 0.689 -width 306 -relwidth 0 \
        -height 23 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent76 \
        -in $top -x 0 -relx 0.347 -y 0 -rely 0.756 -width 306 -relwidth 0 \
        -height 23 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but77 \
        -in $top -x 0 -relx 0.628 -y 0 -rely 0.867 -height 31 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but78 \
        -in $top -x 0 -relx 0.4 -y 0 -rely 0.867 -width 89 -relwidth 0 \
        -height 31 -relheight 0 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top59 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

