#############################################################################
# Generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#  Jul 16, 2020 09:18:29 PM IST  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #727272 -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 590x450+392+191
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1351 738
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Payments"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    label $top.lab43 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 16 -weight bold -slant roman -underline 1 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Payments Page} 
    vTcl:DefineAlias "$top.lab43" "Label1" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra47 \
        -borderwidth 6 -relief groove -background $vTcl(actual_gui_bg) \
        -height 215 -highlightcolor black -width 405 
    vTcl:DefineAlias "$top.fra47" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra47
    label $site_3_0.lab48 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 3 \
        -font {-family {DejaVu Sans} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Card number :} 
    vTcl:DefineAlias "$site_3_0.lab48" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab50 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Name on card :} 
    vTcl:DefineAlias "$site_3_0.lab50" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab51 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text {Cvv :} 
    vTcl:DefineAlias "$site_3_0.lab51" "Label4" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but52 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 5 \
        -font {-family {DejaVu Sans} -size 10 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Confirm 
    vTcl:DefineAlias "$site_3_0.but52" "Button1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent53 \
        -background white -font TkFixedFont -foreground #ffffff \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white 
    vTcl:DefineAlias "$site_3_0.ent53" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent54 \
        -background white -font TkFixedFont -foreground #ffffff \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white 
    vTcl:DefineAlias "$site_3_0.ent54" "Entry2" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent55 \
        -background white -font TkFixedFont -foreground #ffffff \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white 
    vTcl:DefineAlias "$site_3_0.ent55" "Entry3" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab48 \
        -in $site_3_0 -x 20 -y 40 -width 137 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab50 \
        -in $site_3_0 -x 20 -y 70 -width 144 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 30 -y 100 -width 126 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but52 \
        -in $site_3_0 -x 160 -y 140 -anchor nw -bordermode ignore 
    place $site_3_0.ent53 \
        -in $site_3_0 -x 180 -y 40 -anchor nw -bordermode ignore 
    place $site_3_0.ent54 \
        -in $site_3_0 -x 180 -y 70 -anchor nw -bordermode ignore 
    place $site_3_0.ent55 \
        -in $site_3_0 -x 180 -y 100 -anchor nw -bordermode ignore 
    label $top.lab45 \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 21 -weight bold -slant roman -underline 1 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -text {Pharmacy Management System} 
    vTcl:DefineAlias "$top.lab45" "Label5" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab43 \
        -in $top -x 0 -relx 0.136 -y 0 -rely 0.267 -width 0 -relwidth 0.71 \
        -height 0 -relheight 0.113 -anchor nw -bordermode ignore 
    place $top.fra47 \
        -in $top -x 0 -relx 0.153 -y 0 -rely 0.444 -width 0 -relwidth 0.685 \
        -height 0 -relheight 0.478 -anchor nw -bordermode ignore 
    place $top.lab45 \
        -in $top -x 0 -y 0 -rely 0.044 -width 0 -relwidth 0.998 -height 0 \
        -relheight 0.136 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

